import { createClient } from '@supabase/supabase-js';
import { config } from 'dotenv';

config({ path: '.env.local' });

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL;
const serviceRoleKey = process.env.SUPABASE_SERVICE_ROLE_KEY;

if (!supabaseUrl || !serviceRoleKey) {
  console.error('Missing NEXT_PUBLIC_SUPABASE_URL or SUPABASE_SERVICE_ROLE_KEY in .env.local');
  process.exit(1);
}

const supabase = createClient(supabaseUrl, serviceRoleKey);

type MockRecipe = {
  slug: string;
  title: string;
  country: string;
  region: string;
  description: string;
  ingredients: { name: string; amount: number; unit: string }[];
  steps: string[];
  tags: string[];
  image_url: string;
  cook_time: number;
  prep_time: number;
  servings: number;
  difficulty: 'Easy' | 'Medium' | 'Hard';
  category: 'main' | 'dessert' | 'drink' | 'side';
  coordinates: { lat: number; lng: number };
  is_fusion: boolean;
  inspired_by: string[] | null;
  quote: string;
  nutrition: { calories: number; protein: number; carbs: number; fat: number };
  flavor_profile: { sweet: number; salty: number; sour: number; bitter: number; umami: number; spicy: number };
};

const IMG = (id: string) => `https://images.unsplash.com/${id}?w=600&q=80`;

const mocks: MockRecipe[] = [
  // Western Europe
  {
    slug: 'mock-ratatouille',
    title: 'Ratatouille',
    country: 'France',
    region: 'Western Europe',
    description: 'Slow-cooked Provençal vegetable stew.',
    ingredients: [
      { name: 'Aubergine', amount: 1, unit: 'whole' },
      { name: 'Courgette', amount: 2, unit: 'whole' },
      { name: 'Red bell pepper', amount: 1, unit: 'whole' },
      { name: 'Tomatoes', amount: 4, unit: 'whole' },
      { name: 'Garlic', amount: 3, unit: 'cloves' },
      { name: 'Olive oil', amount: 3, unit: 'tbsp' },
      { name: 'Thyme', amount: 1, unit: 'tsp' },
    ],
    steps: [
      'Dice all vegetables into roughly equal cubes.',
      'Sauté garlic in olive oil, then add peppers and aubergine. Cook 8 minutes.',
      'Add courgette and tomatoes with thyme. Simmer 25 minutes until silky.',
      'Season and serve warm with bread.',
    ],
    tags: ['vegetarian', 'summer'],
    image_url: IMG('photo-1572453800999-e8d2d1589b7c'),
    cook_time: 40, prep_time: 15, servings: 4, difficulty: 'Easy', category: 'main',
    coordinates: { lat: 43.95, lng: 4.80 },
    is_fusion: false, inspired_by: null,
    quote: 'Anyone can cook — but only the fearless can be great.',
    nutrition: { calories: 180, protein: 4, carbs: 20, fat: 10 },
    flavor_profile: { sweet: 3, salty: 4, sour: 3, bitter: 1, umami: 5, spicy: 0 },
  },
  {
    slug: 'mock-pasteis-de-nata',
    title: 'Pastéis de Nata',
    country: 'Portugal',
    region: 'Western Europe',
    description: 'Flaky Portuguese custard tarts.',
    ingredients: [
      { name: 'Puff pastry', amount: 1, unit: 'sheet' },
      { name: 'Egg yolks', amount: 6, unit: 'whole' },
      { name: 'Sugar', amount: 200, unit: 'g' },
      { name: 'Whole milk', amount: 240, unit: 'ml' },
      { name: 'Cinnamon stick', amount: 1, unit: 'whole' },
      { name: 'Lemon peel', amount: 1, unit: 'strip' },
    ],
    steps: [
      'Cut pastry into discs and press into muffin tin.',
      'Heat milk with cinnamon and lemon, whisk into yolks and sugar.',
      'Fill cases and bake at 250°C for 12 minutes until blistered.',
      'Cool slightly, dust with cinnamon.',
    ],
    tags: ['sweet', 'bakery'],
    image_url: IMG('photo-1598233847491-f16487adee2f'),
    cook_time: 15, prep_time: 20, servings: 12, difficulty: 'Medium', category: 'dessert',
    coordinates: { lat: 38.70, lng: -9.18 },
    is_fusion: false, inspired_by: null,
    quote: 'A little burnt top is the whole point.',
    nutrition: { calories: 220, protein: 4, carbs: 28, fat: 10 },
    flavor_profile: { sweet: 8, salty: 1, sour: 1, bitter: 1, umami: 2, spicy: 0 },
  },

  // Eastern Europe
  {
    slug: 'mock-pierogi',
    title: 'Potato & Cheese Pierogi',
    country: 'Poland',
    region: 'Eastern Europe',
    description: 'Soft dumplings filled with potato and farmer cheese.',
    ingredients: [
      { name: 'All-purpose flour', amount: 400, unit: 'g' },
      { name: 'Egg', amount: 1, unit: 'whole' },
      { name: 'Warm water', amount: 180, unit: 'ml' },
      { name: 'Potatoes', amount: 500, unit: 'g' },
      { name: 'Farmer cheese', amount: 200, unit: 'g' },
      { name: 'Butter', amount: 60, unit: 'g' },
      { name: 'Onion', amount: 1, unit: 'whole' },
    ],
    steps: [
      'Boil potatoes until tender; mash with cheese and season.',
      'Knead flour, egg, water, and salt into a soft dough. Rest 30 minutes.',
      'Roll thin, cut circles, fill, and seal edges well.',
      'Boil in salted water 3 minutes. Serve with butter and fried onion.',
    ],
    tags: ['comfort', 'vegetarian'],
    image_url: IMG('photo-1619626471854-3c82c65a9c2b'),
    cook_time: 25, prep_time: 60, servings: 4, difficulty: 'Medium', category: 'main',
    coordinates: { lat: 52.23, lng: 21.01 },
    is_fusion: false, inspired_by: null,
    quote: 'Dumplings are patience you can eat.',
    nutrition: { calories: 420, protein: 14, carbs: 62, fat: 12 },
    flavor_profile: { sweet: 2, salty: 5, sour: 1, bitter: 0, umami: 5, spicy: 0 },
  },
  {
    slug: 'mock-goulash',
    title: 'Hungarian Goulash',
    country: 'Hungary',
    region: 'Eastern Europe',
    description: 'Paprika-rich beef stew, the soul of Hungarian cooking.',
    ingredients: [
      { name: 'Beef chuck', amount: 800, unit: 'g' },
      { name: 'Onions', amount: 3, unit: 'whole' },
      { name: 'Sweet paprika', amount: 3, unit: 'tbsp' },
      { name: 'Caraway seeds', amount: 1, unit: 'tsp' },
      { name: 'Tomatoes', amount: 2, unit: 'whole' },
      { name: 'Red pepper', amount: 1, unit: 'whole' },
      { name: 'Beef stock', amount: 750, unit: 'ml' },
    ],
    steps: [
      'Brown beef cubes in batches; set aside.',
      'Soften onions until deep gold, then stir in paprika off the heat.',
      'Return beef with tomato, pepper, caraway, and stock.',
      'Simmer covered 2 hours until tender. Serve with bread or noodles.',
    ],
    tags: ['hearty', 'high-protein'],
    image_url: IMG('photo-1547424450-f0b6e69d1b0f'),
    cook_time: 130, prep_time: 20, servings: 6, difficulty: 'Easy', category: 'main',
    coordinates: { lat: 47.50, lng: 19.04 },
    is_fusion: false, inspired_by: null,
    quote: 'Paprika is not a spice here — it is a mood.',
    nutrition: { calories: 490, protein: 38, carbs: 18, fat: 28 },
    flavor_profile: { sweet: 2, salty: 5, sour: 2, bitter: 1, umami: 8, spicy: 2 },
  },

  // East Asia
  {
    slug: 'mock-mapo-tofu',
    title: 'Mapo Tofu',
    country: 'China',
    region: 'East Asia',
    description: 'Silken tofu in a numbing, spicy Sichuan sauce.',
    ingredients: [
      { name: 'Silken tofu', amount: 400, unit: 'g' },
      { name: 'Pork mince', amount: 150, unit: 'g' },
      { name: 'Doubanjiang', amount: 2, unit: 'tbsp' },
      { name: 'Fermented black beans', amount: 1, unit: 'tbsp' },
      { name: 'Sichuan peppercorns', amount: 1, unit: 'tsp' },
      { name: 'Garlic', amount: 3, unit: 'cloves' },
      { name: 'Spring onion', amount: 2, unit: 'stalks' },
    ],
    steps: [
      'Cube tofu gently; blanch in salted water and drain.',
      'Fry pork until crisp, then add doubanjiang, garlic, and black beans.',
      'Add stock, slide in tofu, simmer 5 minutes, thicken with slurry.',
      'Finish with toasted, crushed Sichuan peppercorns and spring onion.',
    ],
    tags: ['spicy', 'quick'],
    image_url: IMG('photo-1569718212165-3a8278d5f624'),
    cook_time: 15, prep_time: 10, servings: 3, difficulty: 'Medium', category: 'main',
    coordinates: { lat: 30.67, lng: 104.06 },
    is_fusion: false, inspired_by: null,
    quote: 'Málà — the hum you feel after the first bite.',
    nutrition: { calories: 380, protein: 24, carbs: 10, fat: 26 },
    flavor_profile: { sweet: 1, salty: 7, sour: 1, bitter: 2, umami: 9, spicy: 8 },
  },
  {
    slug: 'mock-beef-noodle-soup',
    title: 'Taiwanese Beef Noodle Soup',
    country: 'Taiwan',
    region: 'East Asia',
    description: 'Deep, spiced broth with hand-pulled noodles and tender shin.',
    ingredients: [
      { name: 'Beef shin', amount: 800, unit: 'g' },
      { name: 'Wheat noodles', amount: 400, unit: 'g' },
      { name: 'Doubanjiang', amount: 2, unit: 'tbsp' },
      { name: 'Star anise', amount: 2, unit: 'whole' },
      { name: 'Soy sauce', amount: 80, unit: 'ml' },
      { name: 'Ginger', amount: 30, unit: 'g' },
      { name: 'Bok choy', amount: 2, unit: 'whole' },
    ],
    steps: [
      'Blanch beef, then sear with aromatics and doubanjiang.',
      'Add soy, spices, and water. Simmer 2 hours until spoon-tender.',
      'Cook noodles separately and blanch bok choy.',
      'Assemble bowls with broth, beef, noodles, and greens.',
    ],
    tags: ['soup', 'hearty'],
    image_url: IMG('photo-1552611052-33e04de081de'),
    cook_time: 140, prep_time: 15, servings: 4, difficulty: 'Medium', category: 'main',
    coordinates: { lat: 25.03, lng: 121.57 },
    is_fusion: false, inspired_by: null,
    quote: 'The broth is the recipe.',
    nutrition: { calories: 560, protein: 42, carbs: 58, fat: 18 },
    flavor_profile: { sweet: 2, salty: 7, sour: 1, bitter: 1, umami: 9, spicy: 4 },
  },

  // East Asia (Japan & Korea)
  {
    slug: 'mock-okonomiyaki',
    title: 'Okonomiyaki',
    country: 'Japan',
    region: 'East Asia',
    description: 'Osaka-style savoury cabbage pancake.',
    ingredients: [
      { name: 'Cabbage', amount: 300, unit: 'g' },
      { name: 'Flour', amount: 150, unit: 'g' },
      { name: 'Eggs', amount: 2, unit: 'whole' },
      { name: 'Dashi', amount: 150, unit: 'ml' },
      { name: 'Pork belly slices', amount: 120, unit: 'g' },
      { name: 'Okonomi sauce', amount: 3, unit: 'tbsp' },
      { name: 'Kewpie mayo', amount: 2, unit: 'tbsp' },
    ],
    steps: [
      'Shred cabbage finely. Whisk flour, egg, and dashi into a batter.',
      'Fold cabbage through; shape into thick rounds on a hot griddle.',
      'Lay pork on top, flip, and cook until cabbage is sweet and tender.',
      'Drizzle sauce, mayo, bonito, and aonori.',
    ],
    tags: ['street-food', 'savory'],
    image_url: IMG('photo-1617196034796-73dfa7b1fd56'),
    cook_time: 20, prep_time: 10, servings: 2, difficulty: 'Easy', category: 'main',
    coordinates: { lat: 34.69, lng: 135.50 },
    is_fusion: false, inspired_by: null,
    quote: '"As you like it" — okonomi literally means your call.',
    nutrition: { calories: 520, protein: 22, carbs: 48, fat: 26 },
    flavor_profile: { sweet: 3, salty: 6, sour: 1, bitter: 0, umami: 8, spicy: 0 },
  },
  {
    slug: 'mock-bibimbap',
    title: 'Bibimbap',
    country: 'South Korea',
    region: 'East Asia',
    description: 'Rice bowl layered with seasoned vegetables, beef, and gochujang.',
    ingredients: [
      { name: 'Short-grain rice', amount: 300, unit: 'g' },
      { name: 'Beef mince', amount: 200, unit: 'g' },
      { name: 'Spinach', amount: 100, unit: 'g' },
      { name: 'Bean sprouts', amount: 100, unit: 'g' },
      { name: 'Carrot', amount: 1, unit: 'whole' },
      { name: 'Gochujang', amount: 2, unit: 'tbsp' },
      { name: 'Eggs', amount: 2, unit: 'whole' },
    ],
    steps: [
      'Season beef with soy, garlic, sesame and brown quickly.',
      'Blanch spinach and sprouts; julienne and sauté carrot.',
      'Plate rice, arrange vegetables and beef in sections, top with fried egg.',
      'Serve gochujang on the side to mix at the table.',
    ],
    tags: ['balanced', 'high-protein'],
    image_url: IMG('photo-1498654896293-37aacf113fd9'),
    cook_time: 25, prep_time: 20, servings: 2, difficulty: 'Medium', category: 'main',
    coordinates: { lat: 37.57, lng: 126.98 },
    is_fusion: false, inspired_by: null,
    quote: 'Every bite a new combination.',
    nutrition: { calories: 610, protein: 32, carbs: 72, fat: 22 },
    flavor_profile: { sweet: 3, salty: 6, sour: 1, bitter: 1, umami: 7, spicy: 4 },
  },

  // Southeast Asia
  {
    slug: 'mock-pho-bo',
    title: 'Phở Bò',
    country: 'Vietnam',
    region: 'Southeast Asia',
    description: 'Clear, fragrant beef noodle soup scented with star anise and cinnamon.',
    ingredients: [
      { name: 'Beef bones', amount: 1.5, unit: 'kg' },
      { name: 'Beef brisket', amount: 500, unit: 'g' },
      { name: 'Rice noodles', amount: 400, unit: 'g' },
      { name: 'Star anise', amount: 4, unit: 'whole' },
      { name: 'Cinnamon stick', amount: 1, unit: 'whole' },
      { name: 'Ginger', amount: 60, unit: 'g' },
      { name: 'Fish sauce', amount: 3, unit: 'tbsp' },
    ],
    steps: [
      'Char onion and ginger over a flame until fragrant.',
      'Parboil bones, rinse, then simmer 3 hours with charred aromatics and spices.',
      'Season broth with fish sauce and rock sugar; slice brisket thin.',
      'Serve over noodles with herbs, chili, and lime.',
    ],
    tags: ['soup', 'fragrant'],
    image_url: IMG('photo-1555126634-323283e090fa'),
    cook_time: 180, prep_time: 30, servings: 6, difficulty: 'Hard', category: 'main',
    coordinates: { lat: 21.03, lng: 105.85 },
    is_fusion: false, inspired_by: null,
    quote: 'A bowl of phở is breakfast, lunch, and a hug.',
    nutrition: { calories: 480, protein: 32, carbs: 60, fat: 12 },
    flavor_profile: { sweet: 2, salty: 6, sour: 2, bitter: 1, umami: 8, spicy: 2 },
  },
  {
    slug: 'mock-rendang',
    title: 'Beef Rendang',
    country: 'Indonesia',
    region: 'Southeast Asia',
    description: 'Slow-cooked dry curry from West Sumatra, deeply spiced.',
    ingredients: [
      { name: 'Beef chuck', amount: 1, unit: 'kg' },
      { name: 'Coconut milk', amount: 800, unit: 'ml' },
      { name: 'Shallots', amount: 8, unit: 'whole' },
      { name: 'Garlic', amount: 6, unit: 'cloves' },
      { name: 'Ginger', amount: 40, unit: 'g' },
      { name: 'Galangal', amount: 40, unit: 'g' },
      { name: 'Dried chilies', amount: 10, unit: 'whole' },
    ],
    steps: [
      'Blitz shallots, garlic, ginger, galangal, and chilies into a paste.',
      'Fry paste in oil until fragrant, then add beef and coconut milk.',
      'Simmer uncovered 2 hours, stirring often, until oil separates.',
      'Keep cooking until meat is dark and dry-coated in spice.',
    ],
    tags: ['spicy', 'slow-cooked'],
    image_url: IMG('photo-1631292784640-2b24be784d5d'),
    cook_time: 180, prep_time: 20, servings: 6, difficulty: 'Hard', category: 'main',
    coordinates: { lat: -0.95, lng: 100.35 },
    is_fusion: false, inspired_by: null,
    quote: 'Patience is the final spice.',
    nutrition: { calories: 620, protein: 38, carbs: 10, fat: 48 },
    flavor_profile: { sweet: 2, salty: 5, sour: 1, bitter: 1, umami: 8, spicy: 7 },
  },

  // South Asia
  {
    slug: 'mock-chole-bhature',
    title: 'Chole Bhature',
    country: 'India',
    region: 'South Asia',
    description: 'Spiced chickpea curry with fluffy fried bread.',
    ingredients: [
      { name: 'Chickpeas (dried)', amount: 250, unit: 'g' },
      { name: 'Onions', amount: 2, unit: 'whole' },
      { name: 'Tomatoes', amount: 3, unit: 'whole' },
      { name: 'Garam masala', amount: 2, unit: 'tsp' },
      { name: 'Amchur', amount: 1, unit: 'tsp' },
      { name: 'All-purpose flour', amount: 300, unit: 'g' },
      { name: 'Yogurt', amount: 100, unit: 'g' },
    ],
    steps: [
      'Soak chickpeas overnight; pressure cook with tea bag for color.',
      'Build masala with onion, tomato, garlic-ginger and spices.',
      'Combine with chickpeas; simmer until thick.',
      'Knead dough with yogurt, rest, roll, and deep-fry bhature until puffed.',
    ],
    tags: ['street-food', 'vegetarian'],
    image_url: IMG('photo-1585937421612-70a008356fbe'),
    cook_time: 60, prep_time: 30, servings: 4, difficulty: 'Medium', category: 'main',
    coordinates: { lat: 28.70, lng: 77.10 },
    is_fusion: false, inspired_by: null,
    quote: 'Sunday brunch, Delhi-style.',
    nutrition: { calories: 640, protein: 22, carbs: 92, fat: 20 },
    flavor_profile: { sweet: 2, salty: 5, sour: 3, bitter: 1, umami: 6, spicy: 5 },
  },
  {
    slug: 'mock-kottu-roti',
    title: 'Kottu Roti',
    country: 'Sri Lanka',
    region: 'South Asia',
    description: 'Chopped flatbread stir-fried with egg, vegetables, and curry.',
    ingredients: [
      { name: 'Godamba roti', amount: 4, unit: 'whole' },
      { name: 'Chicken curry', amount: 300, unit: 'g' },
      { name: 'Leek', amount: 1, unit: 'whole' },
      { name: 'Carrot', amount: 1, unit: 'whole' },
      { name: 'Eggs', amount: 2, unit: 'whole' },
      { name: 'Green chili', amount: 2, unit: 'whole' },
      { name: 'Curry leaves', amount: 1, unit: 'sprig' },
    ],
    steps: [
      'Chop roti into thin strips.',
      'Stir-fry leek, carrot, chili, and curry leaves in hot oil.',
      'Scramble eggs, then toss in roti and curry meat with sauce.',
      'Chop rhythmically on the griddle for 2 minutes before serving.',
    ],
    tags: ['street-food', 'quick'],
    image_url: IMG('photo-1625944525533-473f1e3d2d40'),
    cook_time: 15, prep_time: 15, servings: 2, difficulty: 'Easy', category: 'main',
    coordinates: { lat: 6.93, lng: 79.85 },
    is_fusion: false, inspired_by: null,
    quote: 'You hear kottu before you taste it.',
    nutrition: { calories: 580, protein: 26, carbs: 64, fat: 24 },
    flavor_profile: { sweet: 1, salty: 6, sour: 2, bitter: 1, umami: 7, spicy: 5 },
  },

  // Middle East
  {
    slug: 'mock-fattoush',
    title: 'Fattoush',
    country: 'Lebanon',
    region: 'Middle East',
    description: 'Bright Levantine salad with sumac and crisp pita.',
    ingredients: [
      { name: 'Pita bread', amount: 2, unit: 'whole' },
      { name: 'Romaine lettuce', amount: 1, unit: 'head' },
      { name: 'Cucumber', amount: 1, unit: 'whole' },
      { name: 'Tomatoes', amount: 3, unit: 'whole' },
      { name: 'Radish', amount: 4, unit: 'whole' },
      { name: 'Sumac', amount: 1, unit: 'tbsp' },
      { name: 'Pomegranate molasses', amount: 1, unit: 'tbsp' },
    ],
    steps: [
      'Toast pita until golden and snap into shards.',
      'Chop vegetables into bite-sized pieces.',
      'Whisk olive oil, lemon, sumac, and pomegranate molasses.',
      'Toss everything just before serving so pita stays crunchy.',
    ],
    tags: ['fresh', 'vegetarian'],
    image_url: IMG('photo-1540189549336-e6e99c3679fe'),
    cook_time: 5, prep_time: 15, servings: 4, difficulty: 'Easy', category: 'side',
    coordinates: { lat: 33.89, lng: 35.50 },
    is_fusion: false, inspired_by: null,
    quote: 'Sumac turns every summer into Beirut.',
    nutrition: { calories: 210, protein: 6, carbs: 28, fat: 9 },
    flavor_profile: { sweet: 2, salty: 3, sour: 7, bitter: 2, umami: 3, spicy: 0 },
  },
  {
    slug: 'mock-ghormeh-sabzi',
    title: 'Ghormeh Sabzi',
    country: 'Iran',
    region: 'Middle East',
    description: 'Persian herb stew with lamb, kidney beans, and dried lime.',
    ingredients: [
      { name: 'Lamb shoulder', amount: 600, unit: 'g' },
      { name: 'Parsley', amount: 200, unit: 'g' },
      { name: 'Cilantro', amount: 100, unit: 'g' },
      { name: 'Fenugreek leaves', amount: 30, unit: 'g' },
      { name: 'Kidney beans', amount: 200, unit: 'g' },
      { name: 'Dried limes', amount: 4, unit: 'whole' },
      { name: 'Turmeric', amount: 1, unit: 'tsp' },
    ],
    steps: [
      'Finely chop herbs; sauté slowly in oil until very dark green.',
      'Brown onions and lamb with turmeric, then add pierced dried limes.',
      'Combine with herbs, beans, and water; simmer 2 hours.',
      'Serve over saffron basmati rice.',
    ],
    tags: ['stew', 'herb-forward'],
    image_url: IMG('photo-1604329760661-e71dc83f8f26'),
    cook_time: 130, prep_time: 25, servings: 5, difficulty: 'Medium', category: 'main',
    coordinates: { lat: 35.70, lng: 51.42 },
    is_fusion: false, inspired_by: null,
    quote: 'The greener the stew, the better the cook.',
    nutrition: { calories: 520, protein: 36, carbs: 24, fat: 30 },
    flavor_profile: { sweet: 1, salty: 5, sour: 4, bitter: 3, umami: 7, spicy: 1 },
  },

  // North Africa
  {
    slug: 'mock-tagine',
    title: 'Chicken Tagine with Preserved Lemon',
    country: 'Morocco',
    region: 'North Africa',
    description: 'Slow-braised chicken with olives, preserved lemon, and saffron.',
    ingredients: [
      { name: 'Chicken thighs', amount: 1, unit: 'kg' },
      { name: 'Onion', amount: 2, unit: 'whole' },
      { name: 'Preserved lemon', amount: 1, unit: 'whole' },
      { name: 'Green olives', amount: 150, unit: 'g' },
      { name: 'Saffron', amount: 1, unit: 'pinch' },
      { name: 'Ginger', amount: 1, unit: 'tsp' },
      { name: 'Cilantro', amount: 1, unit: 'bunch' },
    ],
    steps: [
      'Marinate chicken with saffron, ginger, garlic, and olive oil.',
      'Layer onions in a tagine, nestle chicken on top, add preserved lemon.',
      'Cover and cook gently 45 minutes without stirring.',
      'Scatter olives and cilantro to finish.',
    ],
    tags: ['aromatic', 'one-pot'],
    image_url: IMG('photo-1535648530671-ff37f0d01dd9'),
    cook_time: 55, prep_time: 20, servings: 4, difficulty: 'Medium', category: 'main',
    coordinates: { lat: 31.63, lng: -7.99 },
    is_fusion: false, inspired_by: null,
    quote: 'The tagine steams its own secrets.',
    nutrition: { calories: 480, protein: 38, carbs: 12, fat: 30 },
    flavor_profile: { sweet: 2, salty: 6, sour: 4, bitter: 1, umami: 7, spicy: 1 },
  },
  {
    slug: 'mock-koshari',
    title: 'Koshari',
    country: 'Egypt',
    region: 'North Africa',
    description: 'Egypt\'s national stacked bowl of rice, lentils, pasta, and tomato sauce.',
    ingredients: [
      { name: 'Rice', amount: 200, unit: 'g' },
      { name: 'Brown lentils', amount: 150, unit: 'g' },
      { name: 'Macaroni', amount: 150, unit: 'g' },
      { name: 'Chickpeas (cooked)', amount: 200, unit: 'g' },
      { name: 'Tomato passata', amount: 400, unit: 'g' },
      { name: 'Garlic', amount: 4, unit: 'cloves' },
      { name: 'Onions', amount: 2, unit: 'whole' },
    ],
    steps: [
      'Fry sliced onions until dark and crisp; reserve.',
      'Cook lentils, rice, and pasta separately.',
      'Make tomato sauce with garlic, vinegar, and chili.',
      'Layer everything; top with sauce, chickpeas, and crispy onions.',
    ],
    tags: ['vegetarian', 'budget'],
    image_url: IMG('photo-1540189549336-e6e99c3679fe'),
    cook_time: 40, prep_time: 15, servings: 4, difficulty: 'Easy', category: 'main',
    coordinates: { lat: 30.05, lng: 31.23 },
    is_fusion: false, inspired_by: null,
    quote: 'Four starches, one soul.',
    nutrition: { calories: 590, protein: 22, carbs: 108, fat: 8 },
    flavor_profile: { sweet: 2, salty: 5, sour: 3, bitter: 1, umami: 6, spicy: 2 },
  },

  // Sub-Saharan Africa
  {
    slug: 'mock-bobotie',
    title: 'Bobotie',
    country: 'South Africa',
    region: 'Sub-Saharan Africa',
    description: 'Spiced minced beef baked under a savoury egg custard.',
    ingredients: [
      { name: 'Beef mince', amount: 700, unit: 'g' },
      { name: 'Onion', amount: 1, unit: 'whole' },
      { name: 'Curry powder', amount: 2, unit: 'tbsp' },
      { name: 'Bread', amount: 2, unit: 'slices' },
      { name: 'Milk', amount: 300, unit: 'ml' },
      { name: 'Eggs', amount: 2, unit: 'whole' },
      { name: 'Apricot jam', amount: 2, unit: 'tbsp' },
      { name: 'Bay leaves', amount: 4, unit: 'whole' },
    ],
    steps: [
      'Sauté onion, add beef, curry powder, jam, vinegar, and soaked bread.',
      'Press into a dish and tuck bay leaves on top.',
      'Whisk eggs with remaining milk; pour over.',
      'Bake at 180°C for 30 minutes until golden and set.',
    ],
    tags: ['comfort', 'aromatic'],
    image_url: IMG('photo-1551782450-a2132b4ba21d'),
    cook_time: 40, prep_time: 20, servings: 5, difficulty: 'Easy', category: 'main',
    coordinates: { lat: -33.92, lng: 18.42 },
    is_fusion: false, inspired_by: null,
    quote: 'Cape Malay in one dish.',
    nutrition: { calories: 520, protein: 30, carbs: 22, fat: 34 },
    flavor_profile: { sweet: 4, salty: 5, sour: 2, bitter: 0, umami: 7, spicy: 2 },
  },
  {
    slug: 'mock-doro-wat',
    title: 'Doro Wat',
    country: 'Ethiopia',
    region: 'Sub-Saharan Africa',
    description: 'Deeply spiced chicken stew with berbere and slow-cooked onions.',
    ingredients: [
      { name: 'Chicken legs', amount: 6, unit: 'whole' },
      { name: 'Red onions', amount: 4, unit: 'whole' },
      { name: 'Berbere', amount: 3, unit: 'tbsp' },
      { name: 'Niter kibbeh', amount: 3, unit: 'tbsp' },
      { name: 'Garlic', amount: 5, unit: 'cloves' },
      { name: 'Ginger', amount: 30, unit: 'g' },
      { name: 'Hard-boiled eggs', amount: 4, unit: 'whole' },
    ],
    steps: [
      'Cook onions low and slow, dry, for 45 minutes until jammy.',
      'Add niter kibbeh, berbere, garlic, and ginger; bloom the spices.',
      'Add chicken and water; simmer 40 minutes.',
      'Fold in scored boiled eggs; serve with injera.',
    ],
    tags: ['spicy', 'slow-cooked'],
    image_url: IMG('photo-1604908176997-125f25cc6f3d'),
    cook_time: 90, prep_time: 20, servings: 6, difficulty: 'Medium', category: 'main',
    coordinates: { lat: 9.03, lng: 38.74 },
    is_fusion: false, inspired_by: null,
    quote: 'Eat it with your hands; the injera is the spoon.',
    nutrition: { calories: 540, protein: 42, carbs: 14, fat: 34 },
    flavor_profile: { sweet: 1, salty: 5, sour: 1, bitter: 2, umami: 8, spicy: 7 },
  },

  // North America
  {
    slug: 'mock-mole-poblano',
    title: 'Mole Poblano',
    country: 'Mexico',
    region: 'North America',
    description: 'Complex chili and chocolate sauce served over turkey or chicken.',
    ingredients: [
      { name: 'Chicken', amount: 1.5, unit: 'kg' },
      { name: 'Dried ancho chilies', amount: 4, unit: 'whole' },
      { name: 'Dried mulato chilies', amount: 3, unit: 'whole' },
      { name: 'Dark chocolate', amount: 40, unit: 'g' },
      { name: 'Toasted almonds', amount: 50, unit: 'g' },
      { name: 'Sesame seeds', amount: 2, unit: 'tbsp' },
      { name: 'Tomatoes', amount: 2, unit: 'whole' },
    ],
    steps: [
      'Toast chilies, seeds, and nuts separately, then soak chilies.',
      'Blend everything with tomatoes, stock, and a cinnamon pinch.',
      'Fry the paste in lard 10 minutes, then add stock to a silky sauce.',
      'Poach chicken; bathe in mole and finish with sesame.',
    ],
    tags: ['festive', 'complex'],
    image_url: IMG('photo-1599974579688-8dbdd335c77f'),
    cook_time: 90, prep_time: 40, servings: 6, difficulty: 'Hard', category: 'main',
    coordinates: { lat: 19.04, lng: -98.20 },
    is_fusion: false, inspired_by: null,
    quote: 'Thirty ingredients. One afternoon. One legend.',
    nutrition: { calories: 640, protein: 44, carbs: 22, fat: 38 },
    flavor_profile: { sweet: 3, salty: 5, sour: 2, bitter: 4, umami: 7, spicy: 5 },
  },
  {
    slug: 'mock-lomo-saltado',
    title: 'Lomo Saltado',
    country: 'Peru',
    region: 'South America',
    description: 'Chifa stir-fry of beef, tomato, onion, and chilies, served with fries and rice.',
    ingredients: [
      { name: 'Beef sirloin', amount: 500, unit: 'g' },
      { name: 'Red onion', amount: 1, unit: 'whole' },
      { name: 'Tomatoes', amount: 2, unit: 'whole' },
      { name: 'Ají amarillo', amount: 1, unit: 'whole' },
      { name: 'Soy sauce', amount: 3, unit: 'tbsp' },
      { name: 'Potato fries', amount: 300, unit: 'g' },
      { name: 'Rice (cooked)', amount: 400, unit: 'g' },
    ],
    steps: [
      'Sear beef strips in a very hot wok.',
      'Add onion, tomato wedges, and ají; toss briefly.',
      'Deglaze with soy sauce and a splash of vinegar.',
      'Fold in crisp fries off the heat; plate with rice.',
    ],
    tags: ['fusion', 'quick'],
    image_url: IMG('photo-1585238342029-2b7a8f3b62a1'),
    cook_time: 15, prep_time: 15, servings: 3, difficulty: 'Easy', category: 'main',
    coordinates: { lat: -12.05, lng: -77.04 },
    is_fusion: true, inspired_by: ['Peruvian', 'Chinese'],
    quote: 'Chifa: where Canton met the Andes.',
    nutrition: { calories: 680, protein: 40, carbs: 72, fat: 26 },
    flavor_profile: { sweet: 2, salty: 7, sour: 2, bitter: 1, umami: 8, spicy: 3 },
  },

  // ════════════════════════════════════════════════════════════════
  //  Batch 2 — 50 additional recipes (30 Europe/Asia, 20 others)
  // ════════════════════════════════════════════════════════════════

  // ── Western Europe (8 more) ─────────────────────────────────
  {
    slug: 'mock-coq-au-vin', title: 'Coq au Vin', country: 'France', region: 'Western Europe',
    description: 'Burgundian braised chicken in red wine.',
    ingredients: [
      { name: 'Chicken', amount: 1.5, unit: 'kg' }, { name: 'Red wine', amount: 500, unit: 'ml' },
      { name: 'Bacon lardons', amount: 150, unit: 'g' }, { name: 'Pearl onions', amount: 200, unit: 'g' },
      { name: 'Mushrooms', amount: 200, unit: 'g' }, { name: 'Thyme', amount: 2, unit: 'sprigs' },
    ],
    steps: ['Brown chicken pieces. Sauté lardons and onions.', 'Deglaze with wine, add thyme.', 'Braise 1.5 hours until tender.', 'Add mushrooms for last 20 min.'],
    tags: ['braised', 'classic'], image_url: IMG('photo-1600891964092-4316c288032e'),
    cook_time: 100, prep_time: 20, servings: 4, difficulty: 'Medium', category: 'main',
    coordinates: { lat: 47.32, lng: 5.04 }, is_fusion: false, inspired_by: null,
    quote: 'Wine transforms a farmyard bird into a feast.', nutrition: { calories: 520, protein: 38, carbs: 12, fat: 28 },
    flavor_profile: { sweet: 2, salty: 5, sour: 3, bitter: 2, umami: 7, spicy: 0 },
  },
  {
    slug: 'mock-quiche-lorraine', title: 'Quiche Lorraine', country: 'France', region: 'Western Europe',
    description: 'Classic savoury custard tart with bacon and Gruyère.',
    ingredients: [
      { name: 'Shortcrust pastry', amount: 1, unit: 'sheet' }, { name: 'Eggs', amount: 4, unit: 'whole' },
      { name: 'Cream', amount: 200, unit: 'ml' }, { name: 'Bacon', amount: 150, unit: 'g' },
      { name: 'Gruyère', amount: 100, unit: 'g' }, { name: 'Nutmeg', amount: 1, unit: 'pinch' },
    ],
    steps: ['Blind bake the pastry shell.', 'Fry bacon, scatter into shell with cheese.', 'Pour over egg-cream mixture.', 'Bake 35 min at 180°C until set and golden.'],
    tags: ['baking', 'brunch'], image_url: IMG('photo-1608039829572-17e0230a9dfc'),
    cook_time: 40, prep_time: 20, servings: 6, difficulty: 'Medium', category: 'main',
    coordinates: { lat: 48.69, lng: 6.18 }, is_fusion: false, inspired_by: null,
    quote: 'A slice of Lorraine is a slice of morning.', nutrition: { calories: 380, protein: 16, carbs: 22, fat: 26 },
    flavor_profile: { sweet: 1, salty: 6, sour: 1, bitter: 0, umami: 6, spicy: 0 },
  },
  {
    slug: 'mock-carbonara', title: 'Carbonara', country: 'Italy', region: 'Western Europe',
    description: 'Roman pasta with guanciale, egg, and pecorino.',
    ingredients: [
      { name: 'Spaghetti', amount: 400, unit: 'g' }, { name: 'Guanciale', amount: 200, unit: 'g' },
      { name: 'Egg yolks', amount: 6, unit: 'whole' }, { name: 'Pecorino Romano', amount: 100, unit: 'g' },
      { name: 'Black pepper', amount: 2, unit: 'tsp' },
    ],
    steps: ['Crisp guanciale slowly. Whisk yolks with pecorino and pepper.', 'Cook spaghetti al dente, reserve pasta water.', 'Toss hot pasta with guanciale off heat, then stir in egg mixture.', 'Add pasta water to reach silky consistency.'],
    tags: ['pasta', 'classic'], image_url: IMG('photo-1612874742237-6526221588e3'),
    cook_time: 15, prep_time: 10, servings: 4, difficulty: 'Medium', category: 'main',
    coordinates: { lat: 41.90, lng: 12.50 }, is_fusion: false, inspired_by: null,
    quote: 'Simplicity is the ultimate sophistication.', nutrition: { calories: 580, protein: 28, carbs: 55, fat: 26 },
    flavor_profile: { sweet: 0, salty: 7, sour: 0, bitter: 1, umami: 8, spicy: 2 },
  },
  {
    slug: 'mock-risotto-milanese', title: 'Risotto alla Milanese', country: 'Italy', region: 'Western Europe',
    description: 'Saffron-infused creamy rice from Milan.',
    ingredients: [
      { name: 'Arborio rice', amount: 320, unit: 'g' }, { name: 'Saffron threads', amount: 1, unit: 'pinch' },
      { name: 'Chicken stock', amount: 1, unit: 'L' }, { name: 'Butter', amount: 60, unit: 'g' },
      { name: 'Parmigiano', amount: 80, unit: 'g' }, { name: 'White wine', amount: 100, unit: 'ml' },
    ],
    steps: ['Toast rice in butter 2 min.', 'Add wine, stir until absorbed.', 'Add stock ladle by ladle, stirring.', 'Finish with saffron, butter, and Parmigiano.'],
    tags: ['risotto', 'saffron'], image_url: IMG('photo-1633964913295-ceb43826e7cd'),
    cook_time: 25, prep_time: 5, servings: 4, difficulty: 'Medium', category: 'main',
    coordinates: { lat: 45.46, lng: 9.19 }, is_fusion: false, inspired_by: null,
    quote: 'Patience is the secret ingredient.', nutrition: { calories: 440, protein: 14, carbs: 58, fat: 16 },
    flavor_profile: { sweet: 1, salty: 5, sour: 1, bitter: 1, umami: 6, spicy: 0 },
  },
  {
    slug: 'mock-paella', title: 'Paella Valenciana', country: 'Spain', region: 'Western Europe',
    description: 'Traditional rice dish from Valencia with rabbit and snails.',
    ingredients: [
      { name: 'Bomba rice', amount: 400, unit: 'g' }, { name: 'Chicken', amount: 500, unit: 'g' },
      { name: 'Green beans', amount: 200, unit: 'g' }, { name: 'Saffron', amount: 1, unit: 'pinch' },
      { name: 'Tomato', amount: 2, unit: 'whole' }, { name: 'Olive oil', amount: 4, unit: 'tbsp' },
    ],
    steps: ['Sear chicken in wide pan.', 'Add grated tomato, cook down.', 'Add water, beans, saffron; boil 20 min.', 'Add rice, cook without stirring until socarrat forms.'],
    tags: ['rice', 'festive'], image_url: IMG('photo-1534080564583-6be75777b70a'),
    cook_time: 45, prep_time: 15, servings: 6, difficulty: 'Hard', category: 'main',
    coordinates: { lat: 39.47, lng: -0.38 }, is_fusion: false, inspired_by: null,
    quote: 'The socarrat is the soul of the pan.', nutrition: { calories: 480, protein: 30, carbs: 55, fat: 14 },
    flavor_profile: { sweet: 2, salty: 5, sour: 2, bitter: 0, umami: 7, spicy: 1 },
  },
  {
    slug: 'mock-gazpacho', title: 'Gazpacho', country: 'Spain', region: 'Western Europe',
    description: 'Chilled Andalusian tomato soup.',
    ingredients: [
      { name: 'Ripe tomatoes', amount: 1, unit: 'kg' }, { name: 'Cucumber', amount: 1, unit: 'whole' },
      { name: 'Bell pepper', amount: 1, unit: 'whole' }, { name: 'Stale bread', amount: 100, unit: 'g' },
      { name: 'Olive oil', amount: 4, unit: 'tbsp' }, { name: 'Sherry vinegar', amount: 2, unit: 'tbsp' },
    ],
    steps: ['Soak bread in water.', 'Blend all vegetables with bread, oil, and vinegar.', 'Pass through a sieve for silky texture.', 'Chill 2 hours. Serve with diced vegetable garnish.'],
    tags: ['cold-soup', 'summer'], image_url: IMG('photo-1529566652340-2c41a1eb6d93'),
    cook_time: 0, prep_time: 20, servings: 4, difficulty: 'Easy', category: 'side',
    coordinates: { lat: 37.39, lng: -5.99 }, is_fusion: false, inspired_by: null,
    quote: 'Summer in a bowl, no fire required.', nutrition: { calories: 150, protein: 3, carbs: 18, fat: 8 },
    flavor_profile: { sweet: 4, salty: 3, sour: 4, bitter: 1, umami: 5, spicy: 0 },
  },
  {
    slug: 'mock-schnitzel', title: 'Wiener Schnitzel', country: 'Germany', region: 'Western Europe',
    description: 'Breaded and fried veal cutlet, golden and crispy.',
    ingredients: [
      { name: 'Veal cutlets', amount: 4, unit: 'whole' }, { name: 'Flour', amount: 100, unit: 'g' },
      { name: 'Eggs', amount: 2, unit: 'whole' }, { name: 'Breadcrumbs', amount: 200, unit: 'g' },
      { name: 'Butter', amount: 100, unit: 'g' }, { name: 'Lemon', amount: 1, unit: 'whole' },
    ],
    steps: ['Pound cutlets thin. Season.', 'Dredge in flour, egg, breadcrumbs.', 'Fry in butter until golden, spooning butter over.', 'Serve with lemon wedge and potato salad.'],
    tags: ['fried', 'classic'], image_url: IMG('photo-1599921841143-819065a55cc6'),
    cook_time: 10, prep_time: 15, servings: 4, difficulty: 'Easy', category: 'main',
    coordinates: { lat: 48.21, lng: 16.37 }, is_fusion: false, inspired_by: null,
    quote: 'Hear it sizzle, see it gold.', nutrition: { calories: 480, protein: 34, carbs: 30, fat: 24 },
    flavor_profile: { sweet: 0, salty: 5, sour: 2, bitter: 0, umami: 5, spicy: 0 },
  },
  {
    slug: 'mock-fish-and-chips', title: 'Fish and Chips', country: 'United Kingdom', region: 'Western Europe',
    description: 'Beer-battered cod with thick-cut chips.',
    ingredients: [
      { name: 'Cod fillets', amount: 4, unit: 'whole' }, { name: 'Flour', amount: 200, unit: 'g' },
      { name: 'Beer', amount: 250, unit: 'ml' }, { name: 'Potatoes', amount: 1, unit: 'kg' },
      { name: 'Malt vinegar', amount: 3, unit: 'tbsp' }, { name: 'Oil for frying', amount: 1, unit: 'L' },
    ],
    steps: ['Cut potatoes into thick chips, par-boil 5 min.', 'Make batter: flour, beer, salt.', 'Fry chips at 160°C then 190°C for crispy double-fry.', 'Batter and fry fish 4-5 min until golden.'],
    tags: ['fried', 'pub-food'], image_url: IMG('photo-1579208030886-b1f5b7f4d5e2'),
    cook_time: 25, prep_time: 15, servings: 4, difficulty: 'Medium', category: 'main',
    coordinates: { lat: 51.51, lng: -0.13 }, is_fusion: false, inspired_by: null,
    quote: 'Salt, vinegar, newspaper optional.', nutrition: { calories: 620, protein: 32, carbs: 58, fat: 28 },
    flavor_profile: { sweet: 0, salty: 6, sour: 3, bitter: 1, umami: 5, spicy: 0 },
  },

  // ── Eastern Europe (7 more) ─────────────────────────────────
  {
    slug: 'mock-moussaka', title: 'Moussaka', country: 'Greece', region: 'Eastern Europe',
    description: 'Layered aubergine and lamb bake with béchamel.',
    ingredients: [
      { name: 'Aubergines', amount: 3, unit: 'whole' }, { name: 'Lamb mince', amount: 500, unit: 'g' },
      { name: 'Tomato sauce', amount: 400, unit: 'ml' }, { name: 'Béchamel', amount: 400, unit: 'ml' },
      { name: 'Cinnamon', amount: 1, unit: 'tsp' }, { name: 'Parmesan', amount: 50, unit: 'g' },
    ],
    steps: ['Slice and grill aubergines.', 'Brown lamb, add tomato sauce and cinnamon.', 'Layer aubergine and meat in dish.', 'Top with béchamel, bake 45 min at 180°C.'],
    tags: ['baked', 'comfort'], image_url: IMG('photo-1585937421612-70a008356fbe'),
    cook_time: 60, prep_time: 30, servings: 6, difficulty: 'Medium', category: 'main',
    coordinates: { lat: 37.98, lng: 23.73 }, is_fusion: false, inspired_by: null,
    quote: 'Layers of history, layers of flavour.', nutrition: { calories: 450, protein: 28, carbs: 20, fat: 28 },
    flavor_profile: { sweet: 2, salty: 5, sour: 3, bitter: 1, umami: 7, spicy: 1 },
  },
  {
    slug: 'mock-spanakopita', title: 'Spanakopita', country: 'Greece', region: 'Eastern Europe',
    description: 'Flaky phyllo pie with spinach and feta.',
    ingredients: [
      { name: 'Spinach', amount: 500, unit: 'g' }, { name: 'Feta', amount: 200, unit: 'g' },
      { name: 'Phyllo dough', amount: 12, unit: 'sheets' }, { name: 'Eggs', amount: 3, unit: 'whole' },
      { name: 'Dill', amount: 3, unit: 'tbsp' }, { name: 'Olive oil', amount: 4, unit: 'tbsp' },
    ],
    steps: ['Wilt spinach, squeeze dry.', 'Mix with crumbled feta, eggs, and dill.', 'Layer phyllo with oil, fill and fold.', 'Bake 40 min at 180°C until golden.'],
    tags: ['baking', 'vegetarian'], image_url: IMG('photo-1598866594042-8c8f5f2b5ec3'),
    cook_time: 40, prep_time: 20, servings: 8, difficulty: 'Medium', category: 'side',
    coordinates: { lat: 39.64, lng: 19.92 }, is_fusion: false, inspired_by: null,
    quote: 'Crispy outside, green and creamy inside.', nutrition: { calories: 280, protein: 12, carbs: 22, fat: 16 },
    flavor_profile: { sweet: 0, salty: 6, sour: 1, bitter: 2, umami: 5, spicy: 0 },
  },
  {
    slug: 'mock-borscht', title: 'Borscht', country: 'Ukraine', region: 'Eastern Europe',
    description: 'Beetroot soup with sour cream.',
    ingredients: [
      { name: 'Beetroot', amount: 500, unit: 'g' }, { name: 'Cabbage', amount: 200, unit: 'g' },
      { name: 'Potatoes', amount: 2, unit: 'whole' }, { name: 'Beef stock', amount: 1.5, unit: 'L' },
      { name: 'Sour cream', amount: 100, unit: 'ml' }, { name: 'Dill', amount: 2, unit: 'tbsp' },
    ],
    steps: ['Simmer shredded beetroot in stock 30 min.', 'Add diced potatoes and cabbage.', 'Cook until tender, season with vinegar.', 'Serve with sour cream and fresh dill.'],
    tags: ['soup', 'winter'], image_url: IMG('photo-1547592166-23ac45744acd'),
    cook_time: 50, prep_time: 15, servings: 6, difficulty: 'Easy', category: 'main',
    coordinates: { lat: 50.45, lng: 30.52 }, is_fusion: false, inspired_by: null,
    quote: 'The deeper the red, the deeper the soul.', nutrition: { calories: 220, protein: 8, carbs: 30, fat: 8 },
    flavor_profile: { sweet: 4, salty: 4, sour: 5, bitter: 2, umami: 5, spicy: 0 },
  },
  {
    slug: 'mock-cevapcici', title: 'Ćevapčići', country: 'Bosnia and Herzegovina', region: 'Eastern Europe',
    description: 'Grilled minced-meat sausages served in flatbread.',
    ingredients: [
      { name: 'Beef mince', amount: 300, unit: 'g' }, { name: 'Lamb mince', amount: 200, unit: 'g' },
      { name: 'Onion', amount: 1, unit: 'whole' }, { name: 'Garlic', amount: 2, unit: 'cloves' },
      { name: 'Somun bread', amount: 4, unit: 'whole' }, { name: 'Kajmak', amount: 100, unit: 'g' },
    ],
    steps: ['Mix meats with garlic, salt, pepper. Rest 2 hours.', 'Form into finger-sized sausages.', 'Grill over charcoal 3-4 min per side.', 'Serve in somun with kajmak and onions.'],
    tags: ['grilled', 'street-food'], image_url: IMG('photo-1555939594-58d7cb561ad1'),
    cook_time: 10, prep_time: 15, servings: 4, difficulty: 'Easy', category: 'main',
    coordinates: { lat: 43.86, lng: 18.41 }, is_fusion: false, inspired_by: null,
    quote: 'The Balkans in one bite.', nutrition: { calories: 420, protein: 30, carbs: 25, fat: 22 },
    flavor_profile: { sweet: 0, salty: 6, sour: 1, bitter: 0, umami: 7, spicy: 1 },
  },
  {
    slug: 'mock-sarmale', title: 'Sarmale', country: 'Romania', region: 'Eastern Europe',
    description: 'Cabbage rolls stuffed with pork and rice.',
    ingredients: [
      { name: 'Sauerkraut leaves', amount: 12, unit: 'leaves' }, { name: 'Pork mince', amount: 500, unit: 'g' },
      { name: 'Rice', amount: 100, unit: 'g' }, { name: 'Onion', amount: 2, unit: 'whole' },
      { name: 'Smoked pork ribs', amount: 200, unit: 'g' }, { name: 'Tomato paste', amount: 3, unit: 'tbsp' },
    ],
    steps: ['Mix mince with rice, onion, paprika.', 'Roll into sauerkraut leaves.', 'Layer with smoked ribs and tomato paste.', 'Slow-cook 3 hours in the oven.'],
    tags: ['slow-cooked', 'festive'], image_url: IMG('photo-1551183053-bf91a1d81141'),
    cook_time: 180, prep_time: 40, servings: 6, difficulty: 'Hard', category: 'main',
    coordinates: { lat: 44.43, lng: 26.10 }, is_fusion: false, inspired_by: null,
    quote: 'Christmas wrapped in a leaf.', nutrition: { calories: 380, protein: 24, carbs: 18, fat: 24 },
    flavor_profile: { sweet: 1, salty: 6, sour: 4, bitter: 0, umami: 6, spicy: 1 },
  },
  {
    slug: 'mock-khachapuri', title: 'Khachapuri', country: 'Georgia', region: 'Eastern Europe',
    description: 'Boat-shaped cheese bread with an egg on top.',
    ingredients: [
      { name: 'Bread dough', amount: 500, unit: 'g' }, { name: 'Sulguni cheese', amount: 300, unit: 'g' },
      { name: 'Feta', amount: 100, unit: 'g' }, { name: 'Eggs', amount: 2, unit: 'whole' },
      { name: 'Butter', amount: 50, unit: 'g' },
    ],
    steps: ['Shape dough into boats.', 'Fill with mixed cheeses.', 'Bake at 230°C until golden and bubbly.', 'Crack an egg and a knob of butter into center; serve immediately.'],
    tags: ['bread', 'cheese'], image_url: IMG('photo-1586190848861-99aa4a171e90'),
    cook_time: 15, prep_time: 20, servings: 2, difficulty: 'Medium', category: 'main',
    coordinates: { lat: 41.72, lng: 44.79 }, is_fusion: false, inspired_by: null,
    quote: 'Cheese, bread, egg — the holy trinity.', nutrition: { calories: 580, protein: 26, carbs: 42, fat: 34 },
    flavor_profile: { sweet: 0, salty: 7, sour: 1, bitter: 0, umami: 6, spicy: 0 },
  },
  {
    slug: 'mock-pljeskavica', title: 'Pljeskavica', country: 'Serbia', region: 'Eastern Europe',
    description: 'Balkan spiced meat patty, grilled and stuffed in lepinja.',
    ingredients: [
      { name: 'Beef mince', amount: 300, unit: 'g' }, { name: 'Pork mince', amount: 200, unit: 'g' },
      { name: 'Onion', amount: 1, unit: 'whole' }, { name: 'Paprika', amount: 1, unit: 'tsp' },
      { name: 'Kajmak', amount: 80, unit: 'g' }, { name: 'Lepinja bread', amount: 4, unit: 'whole' },
    ],
    steps: ['Mix meats with grated onion and paprika.', 'Form wide flat patties.', 'Grill 4 min per side on high heat.', 'Serve in lepinja with kajmak and ajvar.'],
    tags: ['grilled', 'street-food'], image_url: IMG('photo-1568901346375-23c9450c58cd'),
    cook_time: 10, prep_time: 10, servings: 4, difficulty: 'Easy', category: 'main',
    coordinates: { lat: 44.79, lng: 20.46 }, is_fusion: false, inspired_by: null,
    quote: 'The Balkan burger, no bun needed.', nutrition: { calories: 460, protein: 32, carbs: 22, fat: 26 },
    flavor_profile: { sweet: 0, salty: 6, sour: 0, bitter: 0, umami: 7, spicy: 2 },
  },

  // ── East Asia (8 more) ──────────────────────────────────────
  {
    slug: 'mock-kung-pao-chicken', title: 'Kung Pao Chicken', country: 'China', region: 'East Asia',
    description: 'Sichuan stir-fry with peanuts and dried chilies.',
    ingredients: [
      { name: 'Chicken thigh', amount: 500, unit: 'g' }, { name: 'Peanuts', amount: 80, unit: 'g' },
      { name: 'Dried chilies', amount: 10, unit: 'whole' }, { name: 'Sichuan peppercorns', amount: 1, unit: 'tsp' },
      { name: 'Soy sauce', amount: 2, unit: 'tbsp' }, { name: 'Black vinegar', amount: 1, unit: 'tbsp' },
    ],
    steps: ['Velvet chicken: marinate in cornstarch and soy.', 'Fry peppercorns and chilies until fragrant.', 'Flash-fry chicken, add sauce.', 'Toss peanuts in at the end.'],
    tags: ['spicy', 'wok'], image_url: IMG('photo-1525755662778-989d0524087e'),
    cook_time: 10, prep_time: 15, servings: 3, difficulty: 'Medium', category: 'main',
    coordinates: { lat: 30.57, lng: 104.07 }, is_fusion: false, inspired_by: null,
    quote: 'Numbing, crackling, irresistible.', nutrition: { calories: 420, protein: 34, carbs: 16, fat: 24 },
    flavor_profile: { sweet: 2, salty: 6, sour: 3, bitter: 0, umami: 6, spicy: 8 },
  },
  {
    slug: 'mock-dim-sum', title: 'Har Gow', country: 'China', region: 'East Asia',
    description: 'Crystal shrimp dumplings — the king of dim sum.',
    ingredients: [
      { name: 'Shrimp', amount: 300, unit: 'g' }, { name: 'Wheat starch', amount: 150, unit: 'g' },
      { name: 'Tapioca starch', amount: 50, unit: 'g' }, { name: 'Bamboo shoots', amount: 50, unit: 'g' },
      { name: 'Sesame oil', amount: 1, unit: 'tsp' }, { name: 'White pepper', amount: 1, unit: 'pinch' },
    ],
    steps: ['Make translucent dough with boiling water.', 'Chop shrimp, mix with bamboo shoots and sesame oil.', 'Wrap with pleated folds.', 'Steam 7 minutes until translucent.'],
    tags: ['dumplings', 'steamed'], image_url: IMG('photo-1496116218417-1a781b1c416c'),
    cook_time: 10, prep_time: 40, servings: 4, difficulty: 'Hard', category: 'main',
    coordinates: { lat: 22.32, lng: 114.17 }, is_fusion: false, inspired_by: null,
    quote: 'Count the pleats — thirteen is perfection.', nutrition: { calories: 240, protein: 20, carbs: 28, fat: 6 },
    flavor_profile: { sweet: 1, salty: 4, sour: 0, bitter: 0, umami: 7, spicy: 0 },
  },
  {
    slug: 'mock-xiao-long-bao', title: 'Xiao Long Bao', country: 'China', region: 'East Asia',
    description: 'Shanghai soup dumplings filled with pork and broth.',
    ingredients: [
      { name: 'Pork mince', amount: 400, unit: 'g' }, { name: 'Aspic (pork jelly)', amount: 200, unit: 'g' },
      { name: 'Flour', amount: 300, unit: 'g' }, { name: 'Ginger', amount: 2, unit: 'tbsp' },
      { name: 'Soy sauce', amount: 2, unit: 'tbsp' }, { name: 'Shaoxing wine', amount: 1, unit: 'tbsp' },
    ],
    steps: ['Mix pork with chopped aspic, ginger, soy, wine.', 'Roll thin wrappers, pleat 18 folds.', 'Steam in bamboo baskets 8 minutes.', 'Eat with black vinegar and ginger slivers.'],
    tags: ['dumplings', 'steamed'], image_url: IMG('photo-1563245372-f21724e3856d'),
    cook_time: 10, prep_time: 60, servings: 4, difficulty: 'Hard', category: 'main',
    coordinates: { lat: 31.23, lng: 121.47 }, is_fusion: false, inspired_by: null,
    quote: 'Careful — the soup bites back.', nutrition: { calories: 340, protein: 22, carbs: 30, fat: 14 },
    flavor_profile: { sweet: 1, salty: 5, sour: 2, bitter: 0, umami: 8, spicy: 1 },
  },
  {
    slug: 'mock-tonkotsu-ramen', title: 'Tonkotsu Ramen', country: 'Japan', region: 'East Asia',
    description: 'Pork-bone broth ramen from Fukuoka.',
    ingredients: [
      { name: 'Pork bones', amount: 2, unit: 'kg' }, { name: 'Ramen noodles', amount: 400, unit: 'g' },
      { name: 'Chashu pork', amount: 300, unit: 'g' }, { name: 'Soy tare', amount: 4, unit: 'tbsp' },
      { name: 'Soft-boiled egg', amount: 4, unit: 'whole' }, { name: 'Spring onion', amount: 4, unit: 'stalks' },
    ],
    steps: ['Boil bones on high 12 hours, mashing to release collagen.', 'Braise chashu in soy, mirin, sake.', 'Cook noodles 90 seconds, firm.', 'Assemble: tare, broth, noodles, toppings.'],
    tags: ['noodles', 'slow-cooked'], image_url: IMG('photo-1569718212165-3a8278d5f624'),
    cook_time: 720, prep_time: 30, servings: 4, difficulty: 'Hard', category: 'main',
    coordinates: { lat: 33.59, lng: 130.40 }, is_fusion: false, inspired_by: null,
    quote: 'Twelve hours for twelve minutes of slurping.', nutrition: { calories: 620, protein: 38, carbs: 55, fat: 28 },
    flavor_profile: { sweet: 1, salty: 6, sour: 0, bitter: 0, umami: 9, spicy: 1 },
  },
  {
    slug: 'mock-sushi-nigiri', title: 'Nigiri Sushi', country: 'Japan', region: 'East Asia',
    description: 'Hand-pressed vinegared rice with fresh fish.',
    ingredients: [
      { name: 'Sushi rice', amount: 400, unit: 'g' }, { name: 'Tuna (sashimi grade)', amount: 150, unit: 'g' },
      { name: 'Salmon (sashimi grade)', amount: 150, unit: 'g' }, { name: 'Rice vinegar', amount: 3, unit: 'tbsp' },
      { name: 'Wasabi', amount: 1, unit: 'tsp' }, { name: 'Soy sauce', amount: 2, unit: 'tbsp' },
    ],
    steps: ['Season warm rice with vinegar, sugar, salt.', 'Slice fish at an angle into thin pieces.', 'Wet hands, form rice into oval mounds.', 'Dab wasabi, press fish on top. Serve with soy.'],
    tags: ['raw', 'elegant'], image_url: IMG('photo-1579871494447-9811cf80d66c'),
    cook_time: 0, prep_time: 45, servings: 4, difficulty: 'Hard', category: 'main',
    coordinates: { lat: 35.68, lng: 139.69 }, is_fusion: false, inspired_by: null,
    quote: 'Less is everything.', nutrition: { calories: 320, protein: 24, carbs: 40, fat: 6 },
    flavor_profile: { sweet: 2, salty: 4, sour: 3, bitter: 0, umami: 8, spicy: 2 },
  },
  {
    slug: 'mock-kimchi-jjigae', title: 'Kimchi Jjigae', country: 'South Korea', region: 'East Asia',
    description: 'Fermented-kimchi stew with pork and tofu.',
    ingredients: [
      { name: 'Aged kimchi', amount: 400, unit: 'g' }, { name: 'Pork belly', amount: 200, unit: 'g' },
      { name: 'Tofu', amount: 300, unit: 'g' }, { name: 'Gochugaru', amount: 1, unit: 'tbsp' },
      { name: 'Anchovy stock', amount: 500, unit: 'ml' }, { name: 'Spring onion', amount: 3, unit: 'stalks' },
    ],
    steps: ['Sauté pork belly until fat renders.', 'Add kimchi, stir-fry 5 min.', 'Pour in stock, bring to boil.', 'Add tofu, simmer 15 min. Garnish with spring onion.'],
    tags: ['stew', 'fermented'], image_url: IMG('photo-1498654896293-37aacf113fd9'),
    cook_time: 25, prep_time: 10, servings: 3, difficulty: 'Easy', category: 'main',
    coordinates: { lat: 37.57, lng: 126.98 }, is_fusion: false, inspired_by: null,
    quote: 'The older the kimchi, the deeper the stew.', nutrition: { calories: 380, protein: 22, carbs: 12, fat: 26 },
    flavor_profile: { sweet: 1, salty: 6, sour: 5, bitter: 1, umami: 8, spicy: 6 },
  },
  {
    slug: 'mock-japchae', title: 'Japchae', country: 'South Korea', region: 'East Asia',
    description: 'Glass noodles stir-fried with vegetables and beef.',
    ingredients: [
      { name: 'Sweet potato noodles', amount: 250, unit: 'g' }, { name: 'Beef sirloin', amount: 150, unit: 'g' },
      { name: 'Spinach', amount: 100, unit: 'g' }, { name: 'Carrot', amount: 1, unit: 'whole' },
      { name: 'Soy sauce', amount: 3, unit: 'tbsp' }, { name: 'Sesame oil', amount: 2, unit: 'tbsp' },
    ],
    steps: ['Cook noodles, rinse cold.', 'Stir-fry each vegetable and beef separately.', 'Toss everything with soy sauce and sesame oil.', 'Serve room temperature, garnished with sesame seeds.'],
    tags: ['noodles', 'festive'], image_url: IMG('photo-1553163147-622ab57be1c7'),
    cook_time: 20, prep_time: 25, servings: 4, difficulty: 'Medium', category: 'main',
    coordinates: { lat: 35.18, lng: 129.08 }, is_fusion: false, inspired_by: null,
    quote: 'Every strand a thread of celebration.', nutrition: { calories: 360, protein: 18, carbs: 48, fat: 12 },
    flavor_profile: { sweet: 3, salty: 5, sour: 0, bitter: 0, umami: 6, spicy: 0 },
  },
  {
    slug: 'mock-buuz', title: 'Buuz', country: 'Mongolia', region: 'East Asia',
    description: 'Steamed Mongolian dumplings filled with mutton.',
    ingredients: [
      { name: 'Mutton mince', amount: 500, unit: 'g' }, { name: 'Onion', amount: 2, unit: 'whole' },
      { name: 'Flour', amount: 400, unit: 'g' }, { name: 'Garlic', amount: 3, unit: 'cloves' },
      { name: 'Cumin', amount: 1, unit: 'tsp' }, { name: 'Salt', amount: 1, unit: 'tsp' },
    ],
    steps: ['Make dough, rest 30 min.', 'Mix mutton with onion, garlic, cumin.', 'Roll wrappers, fill and pleat closed with hole on top.', 'Steam 20 min until juices bubble through the hole.'],
    tags: ['dumplings', 'steamed'], image_url: IMG('photo-1534422298391-e4f8c172dddb'),
    cook_time: 20, prep_time: 40, servings: 4, difficulty: 'Medium', category: 'main',
    coordinates: { lat: 47.92, lng: 106.91 }, is_fusion: false, inspired_by: null,
    quote: 'Steppe warmth in every fold.', nutrition: { calories: 400, protein: 26, carbs: 35, fat: 18 },
    flavor_profile: { sweet: 0, salty: 5, sour: 0, bitter: 0, umami: 7, spicy: 1 },
  },

  // ── Southeast Asia (4 more) ─────────────────────────────────
  {
    slug: 'mock-green-curry', title: 'Green Curry', country: 'Thailand', region: 'Southeast Asia',
    description: 'Coconut curry with Thai aubergines and basil.',
    ingredients: [
      { name: 'Green curry paste', amount: 3, unit: 'tbsp' }, { name: 'Coconut milk', amount: 400, unit: 'ml' },
      { name: 'Chicken thigh', amount: 400, unit: 'g' }, { name: 'Thai aubergines', amount: 6, unit: 'whole' },
      { name: 'Thai basil', amount: 1, unit: 'cup' }, { name: 'Fish sauce', amount: 2, unit: 'tbsp' },
    ],
    steps: ['Fry curry paste in coconut cream until fragrant.', 'Add chicken, cook 5 min.', 'Pour in remaining coconut milk and aubergines.', 'Simmer 15 min, finish with basil and fish sauce.'],
    tags: ['curry', 'spicy'], image_url: IMG('photo-1455619452474-d2be8b1e70cd'),
    cook_time: 25, prep_time: 10, servings: 4, difficulty: 'Easy', category: 'main',
    coordinates: { lat: 13.76, lng: 100.50 }, is_fusion: false, inspired_by: null,
    quote: 'Green fire, coconut calm.', nutrition: { calories: 420, protein: 28, carbs: 10, fat: 30 },
    flavor_profile: { sweet: 2, salty: 5, sour: 1, bitter: 1, umami: 6, spicy: 7 },
  },
  {
    slug: 'mock-banh-mi', title: 'Bánh Mì', country: 'Vietnam', region: 'Southeast Asia',
    description: 'Vietnamese baguette with pâté, pickled veg, and herbs.',
    ingredients: [
      { name: 'Baguette', amount: 4, unit: 'whole' }, { name: 'Pork pâté', amount: 100, unit: 'g' },
      { name: 'Roast pork', amount: 200, unit: 'g' }, { name: 'Daikon & carrot pickles', amount: 200, unit: 'g' },
      { name: 'Coriander', amount: 1, unit: 'bunch' }, { name: 'Chili sauce', amount: 2, unit: 'tbsp' },
    ],
    steps: ['Split baguette, toast lightly.', 'Spread pâté on both sides.', 'Layer roast pork, pickles, cucumber, coriander.', 'Drizzle chili sauce and Maggi.'],
    tags: ['sandwich', 'street-food'], image_url: IMG('photo-1600688640154-9619e002df30'),
    cook_time: 0, prep_time: 15, servings: 4, difficulty: 'Easy', category: 'main',
    coordinates: { lat: 10.82, lng: 106.63 }, is_fusion: true, inspired_by: ['France', 'Vietnam'],
    quote: 'France meets Vietnam on a crusty stage.', nutrition: { calories: 380, protein: 22, carbs: 38, fat: 16 },
    flavor_profile: { sweet: 2, salty: 5, sour: 4, bitter: 0, umami: 6, spicy: 4 },
  },
  {
    slug: 'mock-nasi-goreng', title: 'Nasi Goreng', country: 'Indonesia', region: 'Southeast Asia',
    description: 'Indonesian fried rice with sweet soy and a fried egg.',
    ingredients: [
      { name: 'Day-old rice', amount: 500, unit: 'g' }, { name: 'Kecap manis', amount: 3, unit: 'tbsp' },
      { name: 'Shrimp paste', amount: 1, unit: 'tsp' }, { name: 'Eggs', amount: 4, unit: 'whole' },
      { name: 'Shallots', amount: 4, unit: 'whole' }, { name: 'Chili', amount: 3, unit: 'whole' },
    ],
    steps: ['Grind shallots, chili, shrimp paste into sambal.', 'Fry sambal, add rice, toss on high heat.', 'Season with kecap manis.', 'Top each plate with a crispy fried egg.'],
    tags: ['fried-rice', 'street-food'], image_url: IMG('photo-1512058564366-18510be2db19'),
    cook_time: 10, prep_time: 10, servings: 4, difficulty: 'Easy', category: 'main',
    coordinates: { lat: -6.21, lng: 106.85 }, is_fusion: false, inspired_by: null,
    quote: 'Yesterday\'s rice, today\'s glory.', nutrition: { calories: 440, protein: 16, carbs: 56, fat: 18 },
    flavor_profile: { sweet: 4, salty: 6, sour: 0, bitter: 0, umami: 7, spicy: 4 },
  },
  {
    slug: 'mock-adobo', title: 'Chicken Adobo', country: 'Philippines', region: 'Southeast Asia',
    description: 'Braised chicken in soy sauce and vinegar.',
    ingredients: [
      { name: 'Chicken', amount: 1, unit: 'kg' }, { name: 'Soy sauce', amount: 80, unit: 'ml' },
      { name: 'Cane vinegar', amount: 80, unit: 'ml' }, { name: 'Garlic', amount: 8, unit: 'cloves' },
      { name: 'Bay leaves', amount: 3, unit: 'whole' }, { name: 'Black peppercorns', amount: 1, unit: 'tsp' },
    ],
    steps: ['Combine chicken, soy, vinegar, garlic, bay, pepper in a pot.', 'Bring to a boil, then simmer 30 min.', 'Remove chicken, reduce sauce.', 'Return chicken, coat in sauce. Serve over rice.'],
    tags: ['braised', 'comfort'], image_url: IMG('photo-1504674900247-0877df9cc836'),
    cook_time: 40, prep_time: 10, servings: 4, difficulty: 'Easy', category: 'main',
    coordinates: { lat: 14.60, lng: 120.98 }, is_fusion: false, inspired_by: null,
    quote: 'Vinegar and patience, that\'s all you need.', nutrition: { calories: 380, protein: 32, carbs: 6, fat: 24 },
    flavor_profile: { sweet: 1, salty: 7, sour: 5, bitter: 0, umami: 7, spicy: 1 },
  },

  // ── South Asia (3 more) ─────────────────────────────────────
  {
    slug: 'mock-butter-chicken', title: 'Butter Chicken', country: 'India', region: 'South Asia',
    description: 'Tandoori chicken in a velvety tomato-cream sauce.',
    ingredients: [
      { name: 'Chicken thigh', amount: 600, unit: 'g' }, { name: 'Yoghurt', amount: 200, unit: 'ml' },
      { name: 'Tomato puree', amount: 400, unit: 'ml' }, { name: 'Cream', amount: 100, unit: 'ml' },
      { name: 'Butter', amount: 60, unit: 'g' }, { name: 'Garam masala', amount: 2, unit: 'tsp' },
    ],
    steps: ['Marinate chicken in yoghurt and spices 4 hours.', 'Grill or broil chicken until charred.', 'Simmer tomato puree with butter and cream.', 'Add chicken, finish with garam masala and kasuri methi.'],
    tags: ['curry', 'creamy'], image_url: IMG('photo-1603894584373-5ac82b2ae328'),
    cook_time: 30, prep_time: 20, servings: 4, difficulty: 'Medium', category: 'main',
    coordinates: { lat: 28.61, lng: 77.21 }, is_fusion: false, inspired_by: null,
    quote: 'Butter makes everything better, even a tandoor.', nutrition: { calories: 480, protein: 34, carbs: 14, fat: 32 },
    flavor_profile: { sweet: 3, salty: 5, sour: 3, bitter: 1, umami: 7, spicy: 3 },
  },
  {
    slug: 'mock-dosa', title: 'Masala Dosa', country: 'India', region: 'South Asia',
    description: 'Crispy fermented rice-lentil crepe with potato filling.',
    ingredients: [
      { name: 'Rice', amount: 300, unit: 'g' }, { name: 'Urad dal', amount: 100, unit: 'g' },
      { name: 'Potatoes', amount: 4, unit: 'whole' }, { name: 'Mustard seeds', amount: 1, unit: 'tsp' },
      { name: 'Curry leaves', amount: 10, unit: 'leaves' }, { name: 'Turmeric', amount: 1, unit: 'tsp' },
    ],
    steps: ['Soak rice and dal 6 hours, grind to batter, ferment overnight.', 'Boil potatoes, make spiced masala filling.', 'Spread thin batter on hot griddle, drizzle oil.', 'Fill with masala, fold. Serve with sambar and chutney.'],
    tags: ['fermented', 'breakfast'], image_url: IMG('photo-1630383249896-424e482df921'),
    cook_time: 5, prep_time: 30, servings: 4, difficulty: 'Medium', category: 'main',
    coordinates: { lat: 12.97, lng: 77.59 }, is_fusion: false, inspired_by: null,
    quote: 'Fermentation is the first chef.', nutrition: { calories: 280, protein: 8, carbs: 50, fat: 6 },
    flavor_profile: { sweet: 1, salty: 4, sour: 3, bitter: 1, umami: 5, spicy: 2 },
  },
  {
    slug: 'mock-biryani', title: 'Hyderabadi Biryani', country: 'India', region: 'South Asia',
    description: 'Layered basmati rice and spiced lamb, sealed and slow-cooked.',
    ingredients: [
      { name: 'Basmati rice', amount: 500, unit: 'g' }, { name: 'Lamb', amount: 600, unit: 'g' },
      { name: 'Yoghurt', amount: 200, unit: 'ml' }, { name: 'Fried onions', amount: 200, unit: 'g' },
      { name: 'Saffron', amount: 1, unit: 'pinch' }, { name: 'Ghee', amount: 4, unit: 'tbsp' },
    ],
    steps: ['Marinate lamb in yoghurt and spices.', 'Par-cook rice with whole spices.', 'Layer rice and lamb in heavy pot with saffron milk.', 'Seal with dough, cook on low 45 min (dum).'],
    tags: ['rice', 'festive'], image_url: IMG('photo-1563379091339-03b21ab4a4f8'),
    cook_time: 60, prep_time: 30, servings: 6, difficulty: 'Hard', category: 'main',
    coordinates: { lat: 17.39, lng: 78.49 }, is_fusion: false, inspired_by: null,
    quote: 'Sealed with dough, opened with anticipation.', nutrition: { calories: 560, protein: 30, carbs: 58, fat: 22 },
    flavor_profile: { sweet: 1, salty: 5, sour: 1, bitter: 0, umami: 7, spicy: 4 },
  },

  // ── Middle East (3 more) ────────────────────────────────────
  {
    slug: 'mock-shawarma', title: 'Chicken Shawarma', country: 'Lebanon', region: 'Middle East',
    description: 'Spiced rotisserie chicken in warm pita with garlic sauce.',
    ingredients: [
      { name: 'Chicken thigh', amount: 800, unit: 'g' }, { name: 'Shawarma spice', amount: 3, unit: 'tbsp' },
      { name: 'Yoghurt', amount: 100, unit: 'ml' }, { name: 'Pita bread', amount: 6, unit: 'whole' },
      { name: 'Toum (garlic sauce)', amount: 100, unit: 'ml' }, { name: 'Pickled turnip', amount: 100, unit: 'g' },
    ],
    steps: ['Marinate chicken in spices and yoghurt 4 hours.', 'Stack on vertical spit or bake at high heat.', 'Shave thin slices.', 'Wrap in pita with toum, pickles, and vegetables.'],
    tags: ['street-food', 'wrap'], image_url: IMG('photo-1529006557810-274b9b2fc783'),
    cook_time: 30, prep_time: 20, servings: 6, difficulty: 'Medium', category: 'main',
    coordinates: { lat: 33.89, lng: 35.50 }, is_fusion: false, inspired_by: null,
    quote: 'The spit turns, the city eats.', nutrition: { calories: 420, protein: 32, carbs: 30, fat: 20 },
    flavor_profile: { sweet: 0, salty: 5, sour: 3, bitter: 0, umami: 6, spicy: 3 },
  },
  {
    slug: 'mock-kabsa', title: 'Kabsa', country: 'Saudi Arabia', region: 'Middle East',
    description: 'Spiced rice with roasted chicken, the national dish of Saudi Arabia.',
    ingredients: [
      { name: 'Basmati rice', amount: 500, unit: 'g' }, { name: 'Whole chicken', amount: 1.5, unit: 'kg' },
      { name: 'Tomatoes', amount: 3, unit: 'whole' }, { name: 'Kabsa spice mix', amount: 3, unit: 'tbsp' },
      { name: 'Loomi (dried lime)', amount: 2, unit: 'whole' }, { name: 'Raisins & almonds', amount: 50, unit: 'g' },
    ],
    steps: ['Brown chicken with spices.', 'Add tomatoes and water, simmer 40 min.', 'Cook rice in the spiced chicken broth.', 'Serve rice topped with chicken, garnish with nuts and raisins.'],
    tags: ['rice', 'festive'], image_url: IMG('photo-1567188040759-fb8a883dc6d8'),
    cook_time: 60, prep_time: 15, servings: 6, difficulty: 'Medium', category: 'main',
    coordinates: { lat: 24.71, lng: 46.68 }, is_fusion: false, inspired_by: null,
    quote: 'Every Saudi table starts here.', nutrition: { calories: 520, protein: 34, carbs: 55, fat: 18 },
    flavor_profile: { sweet: 2, salty: 5, sour: 2, bitter: 0, umami: 6, spicy: 3 },
  },
  {
    slug: 'mock-mansaf', title: 'Mansaf', country: 'Jordan', region: 'Middle East',
    description: 'Lamb cooked in fermented yoghurt (jameed), served over rice.',
    ingredients: [
      { name: 'Lamb shoulder', amount: 1, unit: 'kg' }, { name: 'Jameed', amount: 3, unit: 'balls' },
      { name: 'Rice', amount: 500, unit: 'g' }, { name: 'Pine nuts', amount: 50, unit: 'g' },
      { name: 'Almonds', amount: 50, unit: 'g' }, { name: 'Flatbread', amount: 4, unit: 'sheets' },
    ],
    steps: ['Dissolve jameed in water to make sauce.', 'Simmer lamb in jameed sauce 2 hours.', 'Cook rice, arrange over flatbread on a platter.', 'Top with lamb, pour sauce, garnish with nuts.'],
    tags: ['festive', 'traditional'], image_url: IMG('photo-1585937421612-70a008356fbe'),
    cook_time: 120, prep_time: 20, servings: 8, difficulty: 'Hard', category: 'main',
    coordinates: { lat: 31.95, lng: 35.93 }, is_fusion: false, inspired_by: null,
    quote: 'Hospitality on a platter.', nutrition: { calories: 580, protein: 36, carbs: 50, fat: 24 },
    flavor_profile: { sweet: 1, salty: 5, sour: 4, bitter: 0, umami: 7, spicy: 0 },
  },

  // ── North Africa (3 more) ───────────────────────────────────
  {
    slug: 'mock-shakshuka', title: 'Shakshuka', country: 'Morocco', region: 'North Africa',
    description: 'Eggs poached in spiced tomato and pepper sauce.',
    ingredients: [
      { name: 'Tomatoes', amount: 6, unit: 'whole' }, { name: 'Bell peppers', amount: 2, unit: 'whole' },
      { name: 'Eggs', amount: 6, unit: 'whole' }, { name: 'Cumin', amount: 2, unit: 'tsp' },
      { name: 'Paprika', amount: 1, unit: 'tsp' }, { name: 'Feta', amount: 50, unit: 'g' },
    ],
    steps: ['Sauté peppers and onions.', 'Add crushed tomatoes, cumin, paprika. Simmer 15 min.', 'Make wells, crack in eggs.', 'Cover and cook until whites set. Crumble feta on top.'],
    tags: ['brunch', 'one-pan'], image_url: IMG('photo-1590412200988-a436970781fa'),
    cook_time: 25, prep_time: 10, servings: 3, difficulty: 'Easy', category: 'main',
    coordinates: { lat: 33.97, lng: -6.85 }, is_fusion: false, inspired_by: null,
    quote: 'Sunrise in a skillet.', nutrition: { calories: 280, protein: 18, carbs: 16, fat: 16 },
    flavor_profile: { sweet: 3, salty: 5, sour: 4, bitter: 0, umami: 6, spicy: 3 },
  },
  {
    slug: 'mock-bastilla', title: 'Bastilla', country: 'Morocco', region: 'North Africa',
    description: 'Sweet-savoury pigeon pie in crispy warqa pastry.',
    ingredients: [
      { name: 'Pigeon or chicken', amount: 1, unit: 'kg' }, { name: 'Warqa pastry', amount: 12, unit: 'sheets' },
      { name: 'Almonds', amount: 200, unit: 'g' }, { name: 'Eggs', amount: 6, unit: 'whole' },
      { name: 'Cinnamon', amount: 2, unit: 'tsp' }, { name: 'Icing sugar', amount: 3, unit: 'tbsp' },
    ],
    steps: ['Braise pigeon with onion, spices. Shred meat.', 'Scramble eggs in the braising liquid.', 'Layer pastry, almond-sugar mix, meat, egg.', 'Bake until golden, dust with icing sugar and cinnamon.'],
    tags: ['pastry', 'festive'], image_url: IMG('photo-1541518763-27f5e1eb28dd'),
    cook_time: 45, prep_time: 40, servings: 6, difficulty: 'Hard', category: 'main',
    coordinates: { lat: 34.02, lng: -6.84 }, is_fusion: false, inspired_by: null,
    quote: 'Sweet, savoury, and utterly Moroccan.', nutrition: { calories: 520, protein: 28, carbs: 36, fat: 30 },
    flavor_profile: { sweet: 5, salty: 4, sour: 0, bitter: 1, umami: 6, spicy: 1 },
  },
  {
    slug: 'mock-ful-medames', title: 'Ful Medames', country: 'Egypt', region: 'North Africa',
    description: 'Slow-cooked fava beans with cumin, lemon, and olive oil.',
    ingredients: [
      { name: 'Fava beans', amount: 400, unit: 'g' }, { name: 'Lemon juice', amount: 3, unit: 'tbsp' },
      { name: 'Garlic', amount: 3, unit: 'cloves' }, { name: 'Cumin', amount: 2, unit: 'tsp' },
      { name: 'Olive oil', amount: 3, unit: 'tbsp' }, { name: 'Parsley', amount: 3, unit: 'tbsp' },
    ],
    steps: ['Slow-cook beans overnight until creamy.', 'Mash slightly, season with cumin, lemon, garlic.', 'Drizzle olive oil generously.', 'Serve with warm pita and hard-boiled egg.'],
    tags: ['breakfast', 'vegetarian'], image_url: IMG('photo-1512621776951-a57141f2eefd'),
    cook_time: 480, prep_time: 10, servings: 4, difficulty: 'Easy', category: 'main',
    coordinates: { lat: 30.04, lng: 31.24 }, is_fusion: false, inspired_by: null,
    quote: 'The breakfast of pharaohs.', nutrition: { calories: 260, protein: 14, carbs: 34, fat: 10 },
    flavor_profile: { sweet: 0, salty: 4, sour: 4, bitter: 1, umami: 5, spicy: 1 },
  },

  // ── Sub-Saharan Africa (4 more) ─────────────────────────────
  {
    slug: 'mock-suya', title: 'Suya', country: 'Nigeria', region: 'Sub-Saharan Africa',
    description: 'Peanut-spiced grilled beef skewers.',
    ingredients: [
      { name: 'Beef sirloin', amount: 500, unit: 'g' }, { name: 'Suya spice (yaji)', amount: 4, unit: 'tbsp' },
      { name: 'Peanut powder', amount: 3, unit: 'tbsp' }, { name: 'Onion', amount: 1, unit: 'whole' },
      { name: 'Tomato', amount: 2, unit: 'whole' }, { name: 'Vegetable oil', amount: 2, unit: 'tbsp' },
    ],
    steps: ['Slice beef thin, thread onto skewers.', 'Coat generously with yaji and peanut powder.', 'Grill over charcoal, basting with oil.', 'Serve with sliced onion and tomato.'],
    tags: ['grilled', 'street-food'], image_url: IMG('photo-1555939594-58d7cb561ad1'),
    cook_time: 10, prep_time: 20, servings: 4, difficulty: 'Easy', category: 'main',
    coordinates: { lat: 9.06, lng: 7.49 }, is_fusion: false, inspired_by: null,
    quote: 'Smoke, peanut, heat — the trinity of the night grill.', nutrition: { calories: 380, protein: 34, carbs: 8, fat: 24 },
    flavor_profile: { sweet: 0, salty: 5, sour: 0, bitter: 0, umami: 6, spicy: 6 },
  },
  {
    slug: 'mock-bunny-chow', title: 'Bunny Chow', country: 'South Africa', region: 'Sub-Saharan Africa',
    description: 'Hollowed bread loaf filled with curry, from Durban.',
    ingredients: [
      { name: 'White bread loaf', amount: 1, unit: 'whole' }, { name: 'Lamb', amount: 500, unit: 'g' },
      { name: 'Curry powder', amount: 3, unit: 'tbsp' }, { name: 'Potatoes', amount: 2, unit: 'whole' },
      { name: 'Tomatoes', amount: 3, unit: 'whole' }, { name: 'Coriander', amount: 1, unit: 'bunch' },
    ],
    steps: ['Brown lamb, add curry powder.', 'Add tomatoes, potatoes, and water. Simmer 1 hour.', 'Hollow out bread loaf.', 'Fill with curry. Eat with your hands, tearing the bread.'],
    tags: ['curry', 'street-food'], image_url: IMG('photo-1565557623262-b51c2513a641'),
    cook_time: 60, prep_time: 15, servings: 4, difficulty: 'Medium', category: 'main',
    coordinates: { lat: -29.86, lng: 31.02 }, is_fusion: true, inspired_by: ['India', 'South Africa'],
    quote: 'Durban\'s answer to a bowl — no bowl needed.', nutrition: { calories: 520, protein: 30, carbs: 48, fat: 22 },
    flavor_profile: { sweet: 1, salty: 5, sour: 2, bitter: 0, umami: 6, spicy: 5 },
  },
  {
    slug: 'mock-tibs', title: 'Tibs', country: 'Ethiopia', region: 'Sub-Saharan Africa',
    description: 'Sautéed beef with rosemary, jalapeños, and onion.',
    ingredients: [
      { name: 'Beef cubes', amount: 500, unit: 'g' }, { name: 'Onion', amount: 2, unit: 'whole' },
      { name: 'Jalapeño', amount: 2, unit: 'whole' }, { name: 'Rosemary', amount: 2, unit: 'sprigs' },
      { name: 'Berbere spice', amount: 1, unit: 'tbsp' }, { name: 'Niter kibbeh', amount: 3, unit: 'tbsp' },
    ],
    steps: ['Heat niter kibbeh in a pan until smoking.', 'Sear beef cubes on high heat.', 'Add onions, jalapeños, rosemary.', 'Toss with berbere, serve on injera.'],
    tags: ['sautéed', 'spicy'], image_url: IMG('photo-1504674900247-0877df9cc836'),
    cook_time: 10, prep_time: 10, servings: 3, difficulty: 'Easy', category: 'main',
    coordinates: { lat: 9.02, lng: 38.75 }, is_fusion: false, inspired_by: null,
    quote: 'Quick fire, big reward.', nutrition: { calories: 400, protein: 36, carbs: 8, fat: 24 },
    flavor_profile: { sweet: 0, salty: 5, sour: 0, bitter: 0, umami: 7, spicy: 5 },
  },
  {
    slug: 'mock-nyama-choma', title: 'Nyama Choma', country: 'Kenya', region: 'Sub-Saharan Africa',
    description: 'Kenyan roasted goat meat, charcoal-grilled.',
    ingredients: [
      { name: 'Goat ribs', amount: 1, unit: 'kg' }, { name: 'Salt', amount: 2, unit: 'tsp' },
      { name: 'Lemon', amount: 2, unit: 'whole' }, { name: 'Chili flakes', amount: 1, unit: 'tsp' },
      { name: 'Kachumbari (salsa)', amount: 200, unit: 'g' }, { name: 'Ugali', amount: 400, unit: 'g' },
    ],
    steps: ['Season goat with salt and lemon.', 'Grill slowly over charcoal 45 min, turning often.', 'Rest 10 minutes, then chop.', 'Serve with kachumbari, ugali, and cold beer.'],
    tags: ['grilled', 'social'], image_url: IMG('photo-1544025162-d76694265947'),
    cook_time: 50, prep_time: 10, servings: 4, difficulty: 'Medium', category: 'main',
    coordinates: { lat: -1.29, lng: 36.82 }, is_fusion: false, inspired_by: null,
    quote: 'Weekend plans sorted.', nutrition: { calories: 460, protein: 40, carbs: 30, fat: 20 },
    flavor_profile: { sweet: 0, salty: 5, sour: 3, bitter: 0, umami: 7, spicy: 2 },
  },

  // ── North America (3 more) ──────────────────────────────────
  {
    slug: 'mock-tacos-al-pastor', title: 'Tacos al Pastor', country: 'Mexico', region: 'North America',
    description: 'Spit-roasted pork tacos with pineapple and salsa verde.',
    ingredients: [
      { name: 'Pork shoulder', amount: 800, unit: 'g' }, { name: 'Achiote paste', amount: 3, unit: 'tbsp' },
      { name: 'Pineapple', amount: 4, unit: 'slices' }, { name: 'Corn tortillas', amount: 12, unit: 'whole' },
      { name: 'Coriander', amount: 1, unit: 'bunch' }, { name: 'White onion', amount: 1, unit: 'whole' },
    ],
    steps: ['Marinate pork in achiote, vinegar, spices overnight.', 'Stack on spit with pineapple on top, roast.', 'Shave thin slices as it cooks.', 'Serve on double tortillas with onion, coriander, and salsa.'],
    tags: ['street-food', 'tacos'], image_url: IMG('photo-1551504734-5ee1c4a1479b'),
    cook_time: 120, prep_time: 30, servings: 6, difficulty: 'Hard', category: 'main',
    coordinates: { lat: 19.43, lng: -99.13 }, is_fusion: true, inspired_by: ['Mexico', 'Lebanon'],
    quote: 'Lebanese shawarma met Mexican chilies and never looked back.', nutrition: { calories: 340, protein: 24, carbs: 28, fat: 16 },
    flavor_profile: { sweet: 3, salty: 5, sour: 2, bitter: 0, umami: 6, spicy: 4 },
  },
  {
    slug: 'mock-jerk-chicken', title: 'Jerk Chicken', country: 'Jamaica', region: 'North America',
    description: 'Scotch-bonnet marinated chicken grilled over pimento wood.',
    ingredients: [
      { name: 'Chicken', amount: 1.5, unit: 'kg' }, { name: 'Scotch bonnet', amount: 3, unit: 'whole' },
      { name: 'Allspice', amount: 2, unit: 'tbsp' }, { name: 'Thyme', amount: 4, unit: 'sprigs' },
      { name: 'Soy sauce', amount: 3, unit: 'tbsp' }, { name: 'Lime', amount: 2, unit: 'whole' },
    ],
    steps: ['Blend scotch bonnet, allspice, thyme, soy, lime into marinade.', 'Marinate chicken overnight.', 'Grill slowly over pimento wood or charcoal.', 'Serve with rice and peas and festival.'],
    tags: ['grilled', 'spicy'], image_url: IMG('photo-1532550907401-a500c9a57435'),
    cook_time: 60, prep_time: 20, servings: 6, difficulty: 'Medium', category: 'main',
    coordinates: { lat: 18.11, lng: -77.30 }, is_fusion: false, inspired_by: null,
    quote: 'Fire and allspice, island soul.', nutrition: { calories: 380, protein: 36, carbs: 4, fat: 24 },
    flavor_profile: { sweet: 1, salty: 5, sour: 2, bitter: 0, umami: 5, spicy: 9 },
  },
  {
    slug: 'mock-pupusas', title: 'Pupusas', country: 'El Salvador', region: 'North America',
    description: 'Thick corn cakes stuffed with cheese and beans.',
    ingredients: [
      { name: 'Masa harina', amount: 500, unit: 'g' }, { name: 'Queso', amount: 200, unit: 'g' },
      { name: 'Refried beans', amount: 200, unit: 'g' }, { name: 'Curtido (slaw)', amount: 200, unit: 'g' },
      { name: 'Tomato salsa', amount: 150, unit: 'ml' }, { name: 'Water', amount: 350, unit: 'ml' },
    ],
    steps: ['Mix masa harina with water to form dough.', 'Flatten a ball, fill with cheese and beans, seal.', 'Cook on griddle until golden spots appear, 3 min per side.', 'Serve with curtido and salsa roja.'],
    tags: ['street-food', 'vegetarian'], image_url: IMG('photo-1599974579688-8dbdd335c77f'),
    cook_time: 15, prep_time: 20, servings: 4, difficulty: 'Easy', category: 'main',
    coordinates: { lat: 13.69, lng: -89.22 }, is_fusion: false, inspired_by: null,
    quote: 'El Salvador in your hands.', nutrition: { calories: 320, protein: 14, carbs: 42, fat: 12 },
    flavor_profile: { sweet: 1, salty: 5, sour: 3, bitter: 0, umami: 5, spicy: 1 },
  },

  // ── South America (3 more) ──────────────────────────────────
  {
    slug: 'mock-empanadas', title: 'Empanadas', country: 'Argentina', region: 'South America',
    description: 'Baked pastry pockets stuffed with beef, onion, and olive.',
    ingredients: [
      { name: 'Flour', amount: 500, unit: 'g' }, { name: 'Beef mince', amount: 400, unit: 'g' },
      { name: 'Onion', amount: 3, unit: 'whole' }, { name: 'Hard-boiled egg', amount: 2, unit: 'whole' },
      { name: 'Green olives', amount: 10, unit: 'whole' }, { name: 'Cumin', amount: 2, unit: 'tsp' },
    ],
    steps: ['Make dough, rest 1 hour.', 'Sauté beef and onions with cumin and paprika.', 'Roll discs, fill with meat, egg, olive. Crimp edges.', 'Bake 25 min at 200°C until golden.'],
    tags: ['pastry', 'street-food'], image_url: IMG('photo-1604908176997-125f25cc6f3d'),
    cook_time: 25, prep_time: 40, servings: 12, difficulty: 'Medium', category: 'main',
    coordinates: { lat: -34.60, lng: -58.38 }, is_fusion: false, inspired_by: null,
    quote: 'Hand pies, big flavour.', nutrition: { calories: 280, protein: 14, carbs: 26, fat: 14 },
    flavor_profile: { sweet: 1, salty: 5, sour: 1, bitter: 0, umami: 6, spicy: 1 },
  },
  {
    slug: 'mock-arepas', title: 'Arepas Reinas Pepiadas', country: 'Venezuela', region: 'South America',
    description: 'Corn cakes stuffed with chicken-avocado salad.',
    ingredients: [
      { name: 'Pre-cooked corn flour', amount: 400, unit: 'g' }, { name: 'Chicken', amount: 400, unit: 'g' },
      { name: 'Avocado', amount: 2, unit: 'whole' }, { name: 'Mayonnaise', amount: 3, unit: 'tbsp' },
      { name: 'Lime', amount: 1, unit: 'whole' }, { name: 'Salt', amount: 1, unit: 'tsp' },
    ],
    steps: ['Mix corn flour with water and salt, form thick patties.', 'Cook on griddle then bake until hollow when tapped.', 'Shred chicken, mix with avocado and mayo.', 'Split arepa, stuff with reina pepiada filling.'],
    tags: ['corn', 'street-food'], image_url: IMG('photo-1529006557810-274b9b2fc783'),
    cook_time: 20, prep_time: 15, servings: 4, difficulty: 'Easy', category: 'main',
    coordinates: { lat: 10.49, lng: -66.88 }, is_fusion: false, inspired_by: null,
    quote: 'The queen of Venezuelan street food.', nutrition: { calories: 380, protein: 22, carbs: 36, fat: 18 },
    flavor_profile: { sweet: 0, salty: 4, sour: 2, bitter: 0, umami: 5, spicy: 0 },
  },
  {
    slug: 'mock-ceviche', title: 'Ceviche', country: 'Peru', region: 'South America',
    description: 'Fresh sea bass cured in tiger\'s milk with aji amarillo.',
    ingredients: [
      { name: 'Sea bass', amount: 500, unit: 'g' }, { name: 'Lime juice', amount: 150, unit: 'ml' },
      { name: 'Red onion', amount: 1, unit: 'whole' }, { name: 'Aji amarillo', amount: 1, unit: 'whole' },
      { name: 'Coriander', amount: 1, unit: 'bunch' }, { name: 'Sweet potato', amount: 1, unit: 'whole' },
    ],
    steps: ['Dice fish into cubes.', 'Mix lime juice with aji, ginger, garlic for tiger\'s milk.', 'Toss fish in tiger\'s milk, marinate 2 minutes only.', 'Serve with sliced onion, coriander, and sweet potato.'],
    tags: ['raw', 'citrus'], image_url: IMG('photo-1535399831218-d5bd36d1a6b3'),
    cook_time: 0, prep_time: 20, servings: 4, difficulty: 'Medium', category: 'main',
    coordinates: { lat: -12.05, lng: -77.04 }, is_fusion: false, inspired_by: null,
    quote: 'The lime does the cooking.', nutrition: { calories: 220, protein: 28, carbs: 16, fat: 4 },
    flavor_profile: { sweet: 1, salty: 4, sour: 8, bitter: 0, umami: 6, spicy: 4 },
  },
];

async function main() {
  const { error, data } = await supabase
    .from('recipes')
    .upsert(mocks, { onConflict: 'slug' })
    .select('slug');

  if (error) {
    console.error('Seed failed:', error.message);
    process.exit(1);
  }

  console.log(`Seeded ${data?.length ?? 0} mock recipes.`);
  console.log('To remove them later: delete from recipes where slug like \'mock-%\';');
}

main();
